apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: mycontainer
        image: acrname01example.azurecr.io/example:v1
      imagePullSecrets:
      - name: my-acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
